sudo: false
language: php
php:
- 7.0
env:
  matrix:
  - DISTRO=centos VERSION=5 FLAVOR="salted"
  - DISTRO=centos VERSION=5 FLAVOR="buildenv" BUILD_SETTINGS="-p edge-repo -p build-env"
  - DISTRO=centos VERSION=6 FLAVOR="salted"
  - DISTRO=centos VERSION=6 FLAVOR="buildenv" BUILD_SETTINGS="-p edge-repo -p build-env"
  - DISTRO=centos VERSION=7 FLAVOR="salted"
  - DISTRO=centos VERSION=7 FLAVOR="buildenv" BUILD_SETTINGS="-p edge-repo -p build-env"
  - DISTRO=fedora VERSION=23 FLAVOR="salted"
  - DISTRO=fedora VERSION=23 FLAVOR="buildenv" BUILD_SETTINGS="-p edge-repo -p build-env"
  - DISTRO=fedora VERSION=24 FLAVOR="salted"
  - DISTRO=fedora VERSION=24 FLAVOR="buildenv" BUILD_SETTINGS="-p edge-repo -p build-env"
  - DISTRO=ubuntu VERSION=trusty FLAVOR="salted"
  - DISTRO=ubuntu VERSION=trusty FLAVOR="buildenv" BUILD_SETTINGS="-p build-env"
  - DISTRO=ubuntu VERSION=xenial FLAVOR="salted"
  - DISTRO=ubuntu VERSION=xenial FLAVOR="buildenv" BUILD_SETTINGS="-p build-env"

install:
  - composer install
script:
  - "./bin/upsalter chroot:build ${DISTRO} ${VERSION} ${DISTRO}-${VERSION}-rootfs-${FLAVOR}.tar.bz2 ${BUILD_SETTINGS} -vvv"
deploy:
  file_glob: true
  skip_cleanup: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/*.bz2 
  on:
    tags: true
  provider: releases
  api_key:
    secure: v/sEFwjOa6wjs5DIKOFIE1QCTpqbNWtnylZl4vyWb4IWO9o7e7OoTHrgR3nCHCMLE5eEB59Ulj2rt3e7EwrUdX8Z8v4zxPKnm/cigGhgAfszaPdlTG/X2atoCwf2CLv/cnD+0v5Z614t/+DKAmEdFSrmnTJ3nt8mU5CXB2pZ7L+UN7J525jN6YViXQBtFXeACUwvLe8psFoeZKty3R/FwTT1GX5USURrOs9FHY95KRkr4Xpq6RBTqFaeLOC61DfCXDI8wj/BEXIhoszqbNHtaguu8+FHYRPhrhWA7Hq8iokFnS2skdLtmiRMcblZ4d6GCiHP1k7Zpx/COFyUmwv/TZtG0acMUqGnoAz4ISXosp3SAiCBPbrPzq1LG4RkZ4SEgJv0+UOq9Vy86eZFc81PIQMKJgB0Q6w395yG0KmSytdLkJuqOwE0EOmclKhccMjAo+ECZ4KNF1rD3GJwxxYEfzUz46B4rJfHMrTZZqyrApyqaFjj/tjKCLGwRBbevxY4desg6lEzpR4V8hmJiJZf7UomqWKjncBc0xSIe50riArTG30AFyU7Hc7WMFsZxajt+wh8hbfuUc/YYd48EvkXeHWPd/P8U7+YOmY3oSoC25FHZB4NwtiCjTlfqtkHucANGI2kSt4j8HRiR7P4g5gpYFX0daiV10XIB8ZZoOaBeDM=
